### ISSUE TITLE
NAM sounds wrong..

### ISSUE THREAD

**Issue by BorisSutin** [moddevices/mod-app#11]
NAM produces strange sounds. Feeling like the resampling is wrong. MacOS 13.6 M1Pro

**Comment by ildus** [comment]
For me it's crashing the app. Also MacOS 13.6 M1 Pro.

**Comment by falkTX** [comment]
I wonder if this is an issue of wrong sample-rate. in any case the NAM plugin was broken and crashed, likely now fixed in the latest GH action builds.

Try them if possible, or wait for a new release.

**Comment by falkTX** [comment]
please try with 0.0.3 release https://github.com/moddevices/mod-app/releases/tag/0.0.3
thanks

**Comment by falkTX** [comment]
from your comment on #23 I imply this issue is fixed and can be closed. thanks

**Comment by ildus** [comment]
@falkTX Confirming it is fixed for me too. Thanks!
