### ISSUE TITLE
NO MIDI input in Windows

### ISSUE THREAD

**Issue by raidolo** [moddevices/mod-app#13]
As the subject says... I don't see midi Input in the GUI.

Jackd is started with this command line: 

```
Starting jackd using:
-R -S -C .\jack\jack-session.conf -X winmme -d portaudio -r 48000 -p 128 -P ASIO::Studio USB ASIO Driver -C ASIO::Studio USB ASIO Driver
jackdmp 1.9.21
```

Midi channels works as expected, I can see the commands coming in using Pocket Midi:

![image](https://github.com/moddevices/mod-app/assets/25846804/e109b0a9-43f0-4fe7-8fc6-1fc64033b81c)

**Comment by falkTX** [comment]
this is fixed in the latest builds from github actions, but not present yet on a tagged release.
