### ISSUE TITLE
Does not start.

### ISSUE THREAD

**Issue by MaxZak2020** [moddevices/mod-app#16]
The installation is completed successfully, but the program does not start. I see a circle for a while, and then nothing. Please help me fix this. Thanks a lot..

**Comment by falkTX** [comment]
Potentially fixed with 6c542acc091a1580c935acd6a00217c880b0453e

Can be checked with the GH action builds, or wait till next release.

**Comment by falkTX** [comment]
please try with 0.0.3 release https://github.com/moddevices/mod-app/releases/tag/0.0.3
thanks

**Comment by MaxZak2020** [comment]
Oh my gosh! Thank you so much. It's astonishing breackthrow!
