### ISSUE TITLE
[Linux] Problems selecting a usb audio interface

### ISSUE THREAD

**Issue by protectorateindustrial** [moddevices/mod-app#26]
Hi!

I have problems selecting a usb audio interface (yamaha ag03) from the dropdown in mod app. Usually I have start and shutdown the app around three times for my usb audio interface to appear in the drop down menu. Its visible and selected in the separate audio input drop down but does not appear in the main drop down.

**Comment by protectorateindustrial** [comment]
Works according to my testing.

**Comment by falkTX** [comment]
cool, thanks for checking. closing ticket
