### ISSUE TITLE
Test on mac M1

### ISSUE THREAD

**Issue by BorisSutin** [moddevices/mod-app#6]
Hi!
App runs only from the dmg package folder; if you copy it to the application folder, the window does not open and requests access to the microphone every time. The setting is not saved and creates multiple copies of the application in the privacy section on mac settings. The jack does not start with an external USB card

Starting jackd using:
-R -S -C ./jack/jack-session.conf -d coreaudio -r 48000 -p 128 -P 60 -C 60
Could not find any internals in /private/var/folders/2y/7056xvb513z16w31jv4z9c6h0000gn/T/AppTranslocation/A167A01E-94A0-4FFD-A460-197B8848953E/d/mod-app.app/Contents/MacOS/jack!
Could not find any internals in driver directory!
jackdmp 1.9.22
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Default input and output devices are not the same !!
Cannot open default device
Cannot initialize driver
JackServer::Open failed with -1
Failed to open server

**Comment by falkTX** [comment]
so 2 different issues here, and these are known.

1. app is not signed, leading to that "always asking permission" situation
2. jack2 coreaudio driver always tries to use default audio interface instead of the one selected. need to check if this works well with standard jackd from jack2 or an issue specific to mod-app

**Comment by falkTX** [comment]
I have opened up 2 different tickets for these #7 and #8.

Lets use those for tracking the individual issues there.

**Comment by BorisSutin** [comment]
Cool! I selected the default USB card in the audio settings and now everything works.
1. But I still don’t see the application window, only the icon in the panel.
2. I would like to change the startup options for jack. My card works in Logic 48000 / 32 samples. How to change this, I did not find any configuration files where they are located.
3. And you need to decide what to do with access to the audio device, you indicated the keys in the info.plist

**Comment by BorisSutin** [comment]
![screen1](https://github.com/moddevices/mod-app/assets/6505053/968fbce2-bca2-496c-be60-d655b4411ac0)
but the strangest thing is that each launch of the program creates a separate instance in the privacy settings and it is not clear how to remove them from there)

**Comment by falkTX** [comment]
> * But I still don’t see the application window, only the icon in the panel.

click on it and select "open settings" to bring it back

> * I would like to change the startup options for jack. My card works in Logic 48000 / 32 samples. How to change this, I did not find any configuration files where they are located.

you can only pick between 128 and 256 samples, sample rate is always 48000.
very soon I will add a 64 samples option

> * And you need to decide what to do with access to the audio device, you indicated the keys in the info.plist

I dont know what you mean by this.
